ShinyStore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('items/', include('items.urls')),
    path('', include('shiny.urls')),
    path('', include('users.urls')),
    path('user/', include('users.urls', namespace='user')),
    path('accounts', include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path

from .views import detail, search

app_name = 'items'

urlpatterns = [
    path('search/', search, name='search'),
    path('item/<int:item_id>/', detail, name='detail'),


]

shiny/urls.py
from django.urls import path

from . import views
from .views import index

app_name = 'shiny'

urlpatterns = [
    path('', index, name='index'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

items/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Категория')

    class Meta:
        ordering = ('name', )
        verbose_name_plural = 'Категория'

    def __str__(self):
        return self.name


class Size(models.Model):
    name = models.CharField(max_length=255, verbose_name='Размер')

    class Meta:
        ordering = ('name', )
        verbose_name_plural = 'Размер'

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    size = models.ForeignKey(Size, on_delete=models.PROTECT)
    is_sold = models.BooleanField(default=False)

    class Meta:
        ordering = ('name', )
        verbose_name_plural = 'Предмет'

    def __str__(self):
        return self.name

shiny/models.py
from django.db import models

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')
    username = models.CharField(max_length=25, unique=True, verbose_name='Имя пользователя')
    first_name = models.CharField(max_length=25, verbose_name='Имя')
    last_name = models.CharField(max_length=25, verbose_name='Фамилия')
    email = models.EmailField(max_length=30, verbose_name='Почта')

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

        def __str__(self):
            return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


User = get_user_model()


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your first name',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your last name',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'image',
            'first_name',
            'last_name',
            'username',
            'email'
        )

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

items/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView, ListView

from items.models import Item, Category


# class Search(ListView):
#     template_name = 'base.html'
#
#     def get_queryset(self):
#         return Item.objects.filter(name__icontains=self.request.GET.get('q'))
#
#     def get_context_data(self, object_list=None, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['q'] = self.request.GET.get('q')
#         return context

def search(request):
    search_query = request.GET.get('q')
    if search_query:
        product_list = Item.objects.filter(Q(name__icontains=search_query))
    else:
        product_list = Item.objects.all()

    paginator = Paginator(product_list, 10)  # Пагинация: 10 элементов на странице

    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)

    return render(request, 'items/search_results.html', {'page_object': page_object, 'query': search_query})


def detail(request, item_id):
    item = get_object_or_404(Item, pk=item_id)

    context = {'item': item}

    return render(request, 'items/detail.html', context=context)

shiny/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from items.models import Category, Item


def index(request):
    items = Item.objects.filter(is_sold=False)[0:9]
    categories = Category.objects.all()

    return render(request, 'shiny/index.html', {
        'categories': categories,
        'items': items,
    })

users/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import auth, messages
import shiny.views
from django.contrib.auth import get_user_model

from users.forms import SignupForm, LoginForm, ProfileForm

User = get_user_model()


def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)

    context={
        'title': 'Home - Кабинет',
        'form': form
    }
    return render(request, 'users/profile.html', context)


def registration(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'users/registration.html', {
        'form': form
    })


def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)

        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('shiny:index'))

    else:
        form = LoginForm()

    context = {
        'title': 'Home - Авторизация',
        'form': form
    }

    return render(request, 'users/login.html', context)


@login_required
def logout(request):
    auth.logout(request)
    return redirect(reverse('users:login'))

items/templates/items/detail.html
{% extends 'base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ item.image.url }}" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
        <p class="text-gray-500"><strong>Цена: </strong>{{ item.price }}</p>
        <p class="text-gray-500"><strong>Размер: </strong>{{ item.size }}</p>


        {% if item.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Описание:</strong><br>
                {{ item.description }}
            </p>
        {% endif %}
    </div>
</div>

{% endblock %}

items/templates/items/search_results.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-2xl">Результаты поиска по запросу "{{ query }}"</h1>
    <div class="grid grid-cols-3 gap-3">
        {% for item in page_object %}
            <div>
                    <a href="{% url 'items:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Цена: {{ item.price }} ₽</p>
                        </div>
                    </a>
                </div>
        {% empty %}
            <p>По вашему запросу ничего не найдено.</p>
        {% endfor %}
    </div>
    <div class="pagination">
        <span class="step-links">
            {% if page_object.has_previous %}
                <a href="?page=1">&laquo; первая</a>
                <a href="?page={{ page_object.previous_page_number }}">&lsaquo; предыдущая</a>
            {% endif %}

            <span class="current-page">
                Страница {{ page_object.number }} из {{ page_object.paginator.num_pages }}.
            </span>

            {% if page_object.has_next %}
                <a href="?page={{ page_object.next_page_number }}">следующая &rsaquo;</a>
                <a href="?page={{ page_object.paginator.num_pages }}">последняя &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

shiny/templates/shiny/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} ShinyStore — магазин обуви</title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">ShinyStore<br><small>магазин обуви</small></a>

            <div class="space-x-6">
                <a href="" class="text-lg font-semibold hover:text-gray-500">Каталог</a>
                <a href="" class="text-lg font-semibold hover:text-gray-500">Поиск</a>

                {% if request.user.is_authenticated %}
                    <a href="" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Почта</a>
                    <a href="" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Личный кабинет</a>
                {% else %}
                    <a href="" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Зарегистрироваться</a>
                    <a href="" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Войти</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">О нас</h3>

                <p class="text-lg text-gray-500">ShinyStore — магазин обуви. Здесь вы найдете все на свой вкус и цвет!</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Меню</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">О нас</a></li>
                    <li><a href="" class="text-lg text-teal-500 hover:text-teal-700">Контакты</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Политика конфиденциальности</a></li>

                </ul>
            </div>
        </footer>
    </body>
</html>

shiny/templates/shiny/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Новинки</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'items:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Цена: {{ item.price }} ₽</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Категории</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">предметов {{ category.item_set.count }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} ShinyStore — магазин обуви</title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">ShinyStore<br><small>магазин обуви</small></a>


            <form method="get" action="{% url 'items:search' %}" class="d-flex" role="search">
                <input name="q" class="form-control me-2 px-6 py-3 bg-gray-300 rounded-xl" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success font-semibold text-lg text-white bg-teal-500 rounded-xl px-6 py-3" type="submit"> Поиск</button>
            </form>
            <div class="space-x-6">
                <a href="" class="text-lg font-semibold hover:text-gray-500"></a>
                <a href="{% url 'shiny:contacts' %}" class="text-lg font-semibold hover:text-gray-500">Контакты</a>

                {% if request.user.is_authenticated %}
                    <a href="" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Каталог</a>
                    <a href="{% url 'users:profile' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Личный кабинет</a>
                    <a href="{% url 'users:logout' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Выйти</a>
                {% else %}
                    <a href="{% url 'users:registration' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Зарегистрироваться</a>
                    <a href="{% url 'users:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Войти</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>
        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">О нас</h3>

                <p class="text-lg text-gray-500">ShinyStore — магазин обуви. Здесь вы найдете все на свой вкус и цвет!</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Меню</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">О нас</a></li>
                    <li><a href="{% url 'shiny:contacts' %}" class="text-lg text-teal-500 hover:text-teal-700">Контакты</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Политика конфиденциальности</a></li>

                </ul>
            </div>
        </footer>
    </body>
</html>

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row">
            <!-- Профиль с данными пользователя -->
            <div class="col-md-5">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h1 class="text-center mb-4 text-2xl ">Профиль пользователя</h1>
                    <form action="{% url "users:profile" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 mb-3 text-lg font-semibold">
                                {% if user.image %}
                                    <img src="{{ user.image.url }}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="max-width: 300px;">
                                {% else %}
                                    <img src="{% static "images/avatar.png" %}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="max-width: 300px;">
                                {% endif %}
                                <input type="file" class="form-control mt-3" id="id_image"
                                    name='image'
                                    accept="image/*">
                                    {% if form.image.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_first_name" class="form-label text-lg">Имя:</label>
                                <input type="text" class="py-4 px-6 rounded-xl bg-gray-700 text-white" id="id_first_name"
                                    name="first_name"
                                    placeholder="Введите ваше имя"
                                    value="{{ form.first_name.value }}"
                                    required>
                                    {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_last_name" class="form-label text-lg">Фамилия:</label>
                                <input type="text" class="py-4 px-6 rounded-xl bg-gray-700 text-white" id="id_last_name"
                                    name="last_name"
                                    placeholder="Введите вашу фамилию"
                                    value="{{ form.last_name.value }}"
                                    required>
                                    {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label text-lg">Имя пользователя:</label>
                                <input type="text" class="py-4 px-6 rounded-xl bg-gray-700 text-white" id="id_username"
                                    name="username"
                                    placeholder="Введите ваше имя пользователя"
                                    value="{{ form.username.value }}"
                                    required>
                                    {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label text-lg">Email:</label>
                                <input type="email" class=" py-4 px-6 rounded-xl bg-gray-700 text-white" id="id_email"
                                    name="email"
                                    placeholder="Введите ваш email *youremail@example.com"
                                    value="{{ form.email.value }}"
                                    required>
                                    {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-outline-success font-semibold text-lg text-white bg-teal-500 rounded-xl px-6 py-3">Сохранить</button>
                    </form>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

users/templates/users/registration.html
{% extends 'base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Регистрация</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Имя пользователя</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Имя</label><br>
            {{ form.first_name }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Фамилия</label><br>
            {{ form.last_name }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Пароль</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Повторите пароль</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Зарегистрироваться</button>
    </form>
</div>
{% endblock %}